#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ShakrLabs.ShotShakr.Resource", IsApplication=true)]

namespace ShakrLabs.ShotShakr
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int push_left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int push_left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int push_right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int push_right_out = 2130968579;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int absolute = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int absolute_on = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int coaster = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int coaster1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int coaster10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int coaster2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int coaster3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int coaster4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int coaster5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int coaster6 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int coaster7 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int coaster8 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int coaster9 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int detail = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int drawerbutton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int drawerpull = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int facebook_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int facebook_icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int facebook_icon_small = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int facebook_login = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int flterdrawerbackground = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int gin_off = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int gin_on = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int home = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_menu_share = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int login = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int login_button = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int login_down = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int logout = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int logout_button = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int logout_down = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int rum_off = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int rum_on = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int rumbutton = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int schnapps_off = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int schnapps_on = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int schnappsbutton = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int splash = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tequila = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tequila_off = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tequila_on = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tequilabutton = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int twitter_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int twitter_bg = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int twitter_icon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int vodka_off = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int vodka_on = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int vodkabutton = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int whiskey_off = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int whiskey_on = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int whiskeybutton = 2130837556;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int background_flipper = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int btn_chicken = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int btn_tookthis = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int chkRum = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int chkSchnapps = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int chkTequila = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int chkVodka = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int chkWhiskey = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int coaster = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int coaster2 = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int detail_layout = 2131230739;
			
			// aapt resource value: 0x7f080001
			public const int filterHandle = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int filterSlidingDrawer = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int filtercontent = 2131230722;
			
			// aapt resource value: 0x7f08000e
			public const int flipper = 2131230734;
			
			// aapt resource value: 0x7f080015
			public const int menu_share = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int progressbar = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int shot = 2131230736;
			
			// aapt resource value: 0x7f08000a
			public const int shotIngredients = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int shotName = 2131230729;
			
			// aapt resource value: 0x7f080012
			public const int shot_2 = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int shot_detail = 2131230728;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int filterdrawer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int shot_detail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int shot_picker = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int splash = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ContextMenu = 2131165184;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ShotShakrTheme = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
